/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _XAT_H_RPCGEN
#define _XAT_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define PROGRAMA_XAT 0x20000001
#define VERSION_XAT 1

#if defined(__STDC__) || defined(__cplusplus)
#define getchat 1
extern  char ** getchat_1(void *, CLIENT *);
extern  char ** getchat_1_svc(void *, struct svc_req *);
#define write 2
extern  void * write_1(char **, CLIENT *);
extern  void * write_1_svc(char **, struct svc_req *);
#define numlinies 3
extern  int * numlinies_1(void *, CLIENT *);
extern  int * numlinies_1_svc(void *, struct svc_req *);
extern int programa_xat_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define getchat 1
extern  char ** getchat_1();
extern  char ** getchat_1_svc();
#define write 2
extern  void * write_1();
extern  void * write_1_svc();
#define numlinies 3
extern  int * numlinies_1();
extern  int * numlinies_1_svc();
extern int programa_xat_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_XAT_H_RPCGEN */
