/*
* This is sample code generated by rpcgen.
* These are only templates and you can use them
* as a guideline for developing your own functions.
Jordi Farràs-ls25887
*/
#include<pthread.h>
#include <ncurses.h>
#include <unistd.h>
#include "xat.h"

char *host;
char *login;
int numLinies=-1;
int parent_x, parent_y;
int score_size = 3;
void*threadFunc(void*arg){

	WINDOW *field = newwin(20, parent_x, 0, 0);	
	scrollok(field, TRUE);


	CLIENT *clnt;
	char * *result_1;
	char *getchat_1_arg;
	int  *result_3;
	char *numlinies_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, PROGRAMA_XAT, VERSION_XAT, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif
	while(1){

		result_3 = numlinies_1((void*)&numlinies_1_arg, clnt);
		if (result_3 == (int *) NULL) {
			clnt_perror (clnt, "call failed");
		}else if (*result_3>numLinies){
			werase(field);

			numLinies=*result_3;
			result_1 = getchat_1((void*)&getchat_1_arg, clnt);
			if (result_1 == (char **) NULL) {
				clnt_perror (clnt, "call failed");
			}else	{
				//alarm(1);
				//printf("%s>>> :",argv[2]
				//system("clear");
				wprintw(field,"Welcome %s\n", login);
				wprintw(field,"%s", *result_1);
				wrefresh(field);
			}
			sleep(1);

		}
	}
	//alarm(1);
}
/*
void alarma(){

CLIENT *clnt;
char * *result_1;
char *getchat_1_arg;
int  *result_3;
char *numlinies_1_arg;

#ifndef	DEBUG
clnt = clnt_create (host, PROGRAMA_XAT, VERSION_XAT, "udp");
if (clnt == NULL) {
clnt_pcreateerror (host);
exit (1);
}
#endif
result_3 = numlinies_1((void*)&numlinies_1_arg, clnt);
if (result_3 == (int *) NULL) {
clnt_perror (clnt, "call failed");
}else if (*result_3>numLinies){
numLinies=*result_3;
result_1 = getchat_1((void*)&getchat_1_arg, clnt);
if (result_1 == (char **) NULL) {
clnt_perror (clnt, "call failed");
}else	
alarm(1);
//printf("%s>>> :",argv[2]
//system("clear");

printf("%s\n", *result_1);


}
alarm(1);
}
*/
void
	programa_xat_1(char *host)
{
	WINDOW *score = newwin(23, parent_x, 20, 0);
	CLIENT *clnt;
	char * *result_1;
	char *getchat_1_arg;
	void  *result_2;
	char * write_1_arg;
	int  *result_3;
	char *numlinies_1_arg;
	char aux[500];
	char *enviament=(char*)malloc(sizeof(char)*520);
#ifndef	DEBUG
	clnt = clnt_create (host, PROGRAMA_XAT, VERSION_XAT, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	/*
	move(22,0);
	printw(score,"%s>>>",login);
	wrefresh(score);
	getch();
	*/

	while(1){
		strcpy(aux,"");
		wprintw(score,"\n\n%s>>>",login);
		wrefresh(score);
		move(22,strlen(login)+4);
		getstr(aux);

		strcat(aux,"\n");
		strcpy(enviament,login);
		strcat(enviament,aux);
		werase(score);
		//numLinies++;
		result_2 = write_1(&enviament, clnt);
		if (result_2 == (void *) NULL) {
			clnt_perror (clnt, "call failed");
		}
		//strcpy(write_1_arg,aux);
		/*
		result_2 = write_1(&write_1_arg, clnt);
		if (result_2 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
		}
		*/
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
	main (int argc, char *argv[])
{
	initscr();
	curs_set(FALSE);
	host = argv[1];
	login= argv[2];

	move(22,0);
	printw("%s>>>",login);

	getmaxyx(stdscr, parent_y, parent_x);





	// clean up


	if (argc < 3) {
		printw ("usage: %s server_host nick\n", argv[0]);
		exit (1);
	}



	//printw(field,"....... Welcome %s\n",argv[2]);
	//wrefresh(field);


	pthread_t t1;	
	int s = pthread_create(&t1, NULL, threadFunc," ");
	//signal(SIGALRM,alarma);
	strcat(login,":");
	programa_xat_1 (host);
	exit (0);
}
